language = {
    'PTBR': [
        'Português Brasileiro',
        'Espaço disponível: ',
        'Selecione o idioma de instalação',
        'Idioma',
        'Selecione...',
        'Voltar',
        'Avançar',
        'Cancelar',
        'Eu Concordo',
        'Instalar',
        "Seja bem vindo a instalação do FSLTL Editor.",
        "Este assistente o guiará através da instalação do FSLTL v1.4.",
        "O FSLTL Editor ajuda você a selecionar as Companhias Aéreas instaladas pelo FSLTL da FlybyWire, deixando ativas apenas as Cias. que lhe agradam, auxiliando assim na performance de abertura do Microsoft Flight Simulator 2020.",
        "É recomendado que você feche todos os outros aplicativos antes de iniciar a instalação. Isso tornará possível atualizar arquivos de sistema relevantes sem ter que reiniciar seu computador.",
        "Clique em Avançar para continuar.",
        "Licença.",
        "Por favor, revise os termos da licença antes de instalar o FSLTL Editor.",
        "Se você não concorda com todos os termos deste acordo, não está autorizado a usar o programa FSLTL Editor.",
        "1. Exceto onde indicado de outra forma, toda a documentação e software incluídos no pacote do FSLTL Editor são de direitos autorais de Judenilson Araujo.",
        "2. Você concorda em não fazer engenharia reversa, descompilar, desmontar, alterar, distribuir para lucro ou alugar o software.",
        "3. O software é fornecido “COMO ESTÁ” sem garantias quanto ao desempenho de comerciabilidade ou quaisquer outras garantias, expressas ou implícitas. Em particular, não há garantia para o recurso de desfazer opcional fornecido pela lixeira do Windows. Como alguns softwares desativam esse recurso, não há garantia de adequação para um propósito particular oferecido. Você concorda expressamente que o uso do software é por sua conta e risco.",
        "4. Em nenhum caso o autor será responsável para qualquer parte:",
        "4a. Por quaisquer danos diretos, indiretos, especiais, punitivos, incidentais ou consequenciais (incluindo, mas não se limitando a, danos por perda de lucros comerciais, interrupção de negócios, perda de programas ou informações e similares), ou quaisquer outros danos decorrentes de qualquer maneira do uso, confiança ou incapacidade de usar o programa, mesmo que o autor tenha sido avisado da possibilidade de tais danos.",
        "4b. Por qualquer reivindicação atribuível a erros, omissões ou outras imprecisões em, ou propriedades destrutivas de qualquer informação. O autor reserva-se o direito de não ser responsável pela correção, completude ou qualidade do software fornecido. Reivindicações de responsabilidade referentes a danos causados pelo uso do CloneSpy serão, portanto, rejeitadas.",
        "5. Todos os direitos autorais do software permanecem com o autor.",
        "Se você aceitar os termos do acordo, clique em “Eu concordo” para continuar. Você deve aceitar o acordo para instalar o FSLTL Editor.",
        "Local de Instalação.",
        "Escolha a pasta para extração do FSLTL Editor.",
        "O instalador extrairá todos os arquivos do FSLTL Editor na pasta selecionada.",
        "Para extrair em um local diferente, clique em Procurar e selecione outra pasta.",
        "Clique em Avançar para continuar.",
        'Pasta destino:',
        'Procurar...',
        "Espaço Requerido: 200 MB",
        "Parabéns!",
        "Instalação concluída com sucesso!",
        'Para executar o programa vá até a pasta de instalação e execute o arquivo "fsltleditor.exe"',
        'Para desinstalar o programa, basta apagar a pasta "FSLTL Editor" do local que você instalou. O programa não instala nada no seu Sistema Operacional em outros lugares, nem altera seus registros do windows.',
        "Divirta-se!",
        'Fechar',

    ],
    'ENG': [
        'English',
        'Available space:',
        'Select installation language',
        'Language',
        'Select...',
        'Back',
        'Next',
        'Cancel',
        'I Agree',
        'Install',
        "Welcome to the FSLTL Editor installation.",
        "This wizard will guide you through the installation of FSLTL v1.4.",
        "The FSLTL Editor helps you select the Airlines installed by FSLTL from FlybyWire, leaving only the Airlines that please you active, thus assisting in the opening performance of Microsoft Flight Simulator 2020.",
        "It is recommended that you close all other applications before starting the installation. This will make it possible to update relevant system files without having to restart your computer.",
        "Click Next to continue.",
        "License.",
        "Please review the license terms before installing the FSLTL Editor.",
        "If you do not agree to all the terms of this agreement, you are not authorized to use the FSLTL Editor program.",
        "1. Except where indicated otherwise, all documentation and software included in the FSLTL Editor package are copyrighted by Judenilson Araujo.",
        "2. You agree not to reverse engineer, decompile, disassemble, alter, distribute for profit, or rent the software.",
        "3. The software is provided 'AS IS' without warranties regarding performance or any other warranties, express or implied. In particular, there is no warranty for the optional undo feature provided by the Windows Recycle Bin. As some software disables this feature, there is no warranty of fitness for a particular purpose offered. You expressly agree that the use of the software is at your own risk.",
        "4. In no event shall the author be liable for any damages whatsoever:",
        "4a. For any direct, indirect, special, punitive, incidental, or consequential damages (including, but not limited to, damages for loss of commercial profits, business interruption, loss of programs or information, and the like), or any other damages arising in any way from the use, reliance, or inability to use the program, even if the author has been advised of the possibility of such damages.",
        "4b. For any claims attributable to errors, omissions, or other inaccuracies in, or destructive properties of any information. The author reserves the right not to be responsible for the correctness, completeness, or quality of the software provided. Claims of liability regarding damage caused by the use of CloneSpy will therefore be rejected.",
        "5. All copyrights of the software remain with the author.",
        "If you accept the terms of the agreement, click 'I Agree' to continue. You must accept the agreement to install the FSLTL Editor.",
        "Installation Location.",
        "Choose the folder for FSLTL Editor extraction.",
        "The installer will extract all FSLTL Editor files into the selected folder.",
        "To extract to a different location, click Browse and select another folder.",
        "Click Next to continue.",
        'Destination Folder:',
        'Browse...',
        "Required Space: 200 MB",
        "Congratulations!",
        "Installation completed successfully!",
        'To run the program, go to the installation folder and run the "fsltleditor.exe" file.',
        "To uninstall the program, simply delete the 'FSLTL Editor' folder from the location you installed it. The program does not install anything on your Operating System elsewhere, nor does it alter your windows registry.",
        "Enjoy!",
        'Close',
    ],
}
